package:
  name: cling_ubuntu16
  version: 0.0.1

source:
  fn: cling_2017-01-01_ubuntu16.tar.bz2 
  url: https://root.cern.ch/download/cling/cling_2017-01-01_ubuntu16.tar.bz2

build:
  number: 0

requirements:
  build:
    - python
    - traitlets
    - ipykernel
  run:
    - python
    - notebook

about:
  home: https://root.cern.ch/cling
  license: LGPL
  summary: 'Cling - The Interactive C++ Interpreter'

  # The remaining entries in this section are optional, but recommended
  description: |
    Cling is an interactive C++ interpreter, built on the top of LLVM and
    Clang libraries. Its advantages over the standard interpreters are that
    it has command line prompt and uses just-in-time (JIT) compiler for compilation.
    Many of the developers (e.g. Mono in their project called CSharpRepl (link is external))
    of such kind of software applications name them interactive compilers.    

  doc_url: https://root.cern.ch/cling
  dev_url: https://github.com/root-mirror/cling

extra:
  recipe-maintainers:
    - SylvainCorlay
